# conf/accelerate_no_ds_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
machine_rank: 0
main_process_ip: null
main_process_port: 29500
num_machines: 1

# <<< change this to the number of GPUs you want to use >>>
num_processes: 3

use_cpu: false

# turn on fp16, turn off any DeepSpeed
mixed_precision: fp16
downcast_bf16: "no"
deepspeed_config: null
