# ---------- common defaults shared by all runs ----------
defaults:
  - override /hydra/job_logging: disabled   # keep stdout clean

# ------------------- model settings --------------------
model:
  name: Qwen/Qwen1.5-7B   # fits across 4×A16 in fp16
  load_4bit: true        # set true for 4-bit quant

# ------------------- LoRA settings ---------------------
lora:
  r: 64          # rank
  alpha: 128
  dropout: 0.05
  target_modules:   # projected layers to adapt
    - q_proj
    - v_proj
    - up_proj
    - gate_proj
    - down_proj

# --------------- self-edit sampling --------------------
self_edits:
  samples_per_ctx: 5   # paper uses M = 5 (knowledge) or 15 (ARC)

# -------------- reinforcement loop ---------------------
rl:
  max_rounds: 2          # R in paper
  reward_threshold: 0.05 # Δmetric needed to accept

# --------------- DeepSpeed config path -----------------
deepspeed_config: ds_z3_A16.json
